apiVersion: v1
kind: Secret
metadata:
  name: restock-watcher-secrets
stringData:
  discord-webhook-url: ENC[AES256_GCM,data:Apcn1uwUcy9Lby08r2Zidm8xAg6+M3DUNm+tC0VO2s/vhvnjxt4gBuqox3iXF8BpA6IHyotpzdo5VsEgyGYsyMrrc3bAdXIv/NFEz3sBELyTaDMhMFCTbqgMwOLN3Sd6Gx9KytP0P43rbWuyHAT3yrBe0VDzz8MkTg==,iv:d8n+ftXg+vY/krEFNnUqp0W8dGJBH/1IoP4syPLs4Nk=,tag:uWfnNsUWQzf+vSAHVeVAPw==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZzY3WXFSSHIwejdLUjI0
        YUJqdUR6K2ZPYWc3VjQ5cXFVQXlCWkxuaEFBCjR3ODRXR3B1ZzRkaFhHTTI5NG5I
        TldESGdtQVBRdVhCQWhheEl5Y0VYTDgKLS0tIGhBVHRTNG5SS0xCSXNKWXlmek5Y
        c0ZSZHlPaXhXSXNENlhqRmFaZkxCbWsKpPIjZcGK5Sr7UsJ4PUeetB1ZJQXBEOyg
        DQGGMY5pHd0KntyASWv8WwCMr2oOhbm/qIvdz4KCFAWhX0pyGTC5Bw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-06T20:06:31Z"
  mac: ENC[AES256_GCM,data:gfwHKmjqDu2a0kpk3VJpS4bx/rJam6JxJnBZSAka/S9lGElVJsLpPVhBjDPooL6vqIJmwAJBVI4dpW31wgfiyxxhYVtBokZOQ3ptIeUeV/dWr5Rq6sKC+AMm1iu/qTj2lW2iPV9OJVDN1nxSJ9PingaDExy88FK314jW2y9Z44E=,iv:6gkZDceh/J4cOzZEaYTAsJq0x7nrAlc4LXaqC3y1Jzs=,tag:m2lSm4wqb9+eYQBBfv6Emg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
