---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation

resources:
  - ./secret.sops.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./service-outpost.yaml
  - ./ingress.yaml
  - ./ingress-ui.yaml
  - ./ingress-outpost.yaml
  - ./networkpolicy.yaml
  - ./backup-cronjob.yaml

configMapGenerator:
  - name: kcal-assistant-backup-script
    files:
      - backup.ts
