apiVersion: v1
kind: Secret
metadata:
  name: kcal-assistant-secrets
  namespace: home-automation
type: Opaque
stringData:
  MCP_TOKEN: ENC[AES256_GCM,data:uHDOSc/TwGNKSatOoi28LzcMHxWUnaSr4p1IF5LqPR4Tr08qG8SdozeHwBVprx/3mbMM54LGRXxYxKf/gl//Kg==,iv:tolRZwwfmJCtkV8fp2OUMY0+bEGcfOwKwv9h32ygbOk=,tag:bxdl6VsH2yK2L3bpsx6Www==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSWNFVTV0dHlPUkMzdXkw
        YjEvRi9HZkpoSXFTUXA2bmZLWkk2YzZyNEU0CnFwZjhmanc2WmJTYmlJUXlhLyty
        SkhVNFBpTXVSekFxd0FBdExpU1psR0UKLS0tIHBWYUVzYlV3UU9MdE9IRWpZeFE5
        Q0NreEVacmZCcTNaMGJmVlpQTnVBSEEKeGwtmdPL+QM5fIB9KD9tkW2LHMGK684B
        zmVdYNZ22llTulkAiO9yhuHIeC16akJFuK4oNdwhEk0ZDT/C63xgXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-06T16:26:28Z"
  mac: ENC[AES256_GCM,data:1Njgwqw9mXkOhFeuM9SwucLjUJ8VU86E6nvgUD7qSCKCsOjytuhzPaTJk2Ub8MSrxdSonQ5tnkKUGEEDaxXlkAVJY0uVYs0a6NpcSvYcOExnmQcPpJ+Z6jo3mLCR5NeglUUuRl3DRA7/L1inRPeAmGqOD8dsjJuiTyz1Z2C07ho=,iv:Pi1g7US6emPwv2/JNWwfaGJprp69idxcfhLh8qg/pvc=,tag:hreXJPsaX8m4puWz6WYl+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
