apiVersion: v1
kind: Service
metadata:
  name: kcal-assistant
  labels:
    app: kcal-assistant

spec:
  type: ClusterIP
  selector:
    app: kcal-assistant
  ports:
    - name: http
      port: 3000
      targetPort: 3000
