apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 47.5.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: false
    alertmanager:
      enabled: false
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    # persistence:
    #   enabled: true
    #   storage:
    #     volumeClaimTemplate:
    #       spec:
    #         accessModes: ["ReadWriteOnce"]
    #         resources:
    #           requests:
    #             storage: 10Gi
