apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - nas-targets.yaml
  - nas-alerts.yaml
  - homelab-status.yaml
  - flux-podmonitor.yaml
  - alertmanager-config.yaml
  - alertmanager-ha-webhook.sops.yaml
