# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:yPPsMea7j17qRgxs2u5jAcPboNv2PW1sNQKlU0qvXl+eRe06M9ul3aWl3YqmVJtPQhQ0rJVs2XlyTBHsmsoOjA+Zb+MrcdPW8DVpPownS8syiCQoUiTZcO5i478rkgRDFRedKogiNlPfC5OS8xKGtY3KqZOmk8o+FW4OdQ1uw2oyZjWURtkVavVwlpCtelsyCVWryh/sHZvNwRiUC5c6qq0AEuLU0ZIxaSk4sB+SUKQQwnySVg==,iv:jmjOdGZ+4/wlNNagT17CaeRYQC5tys1+QY6svxpZC0I=,tag:8g7I9bYiKUKN14ahsOqWAQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dVhKanRCUXdJKzRyL3RQ
        aTh1R3d0ODFjWXg4RFo1Yy8vVGdDSmdUTWxVClRneHhpQm84TTRRT25GdGZsSkxJ
        cFBBL3dLeGlZcFlrY3Q5RHJOcWY2d00KLS0tIDM1dGcxTmxKcksrYkJDZ2ZoUDd1
        UG5ONTBZMTAwR0xwUi9wb000d08ybGcKshiLbJhqm+6drWLhjqCBZhysu7PHOdjV
        wBvduU2bx7bNAWlwM7HAaQhF1DE8HXKe9IUQIskz2wIoEHlRCmSN+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T15:02:12Z"
  mac: ENC[AES256_GCM,data:dL9wD+GXRKNTvg7BUthtcX/rn2El2+2cxd+5oYN8zByqZK1ufF+zLAZGVAcOR4IZfEATWmmW4V9rcJcJxDpgQki2uHOgO5As8OxE9Dx4Fk1SM9Vh7kq6Yt6/9muAckyor4f7MDhPnCHpsfEdIpMULGE3r01uq0LpTGOnsKNwEbU=,iv:ziIsM4bfHphqtWs2L/MoomPcuWh6h4c4s2ftw/WCic0=,tag:9EUO6Ulx1MtqRBknt1yxtw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
