apiVersion: v1
kind: Endpoints
metadata:
  name: ugreen-nas-arr-stack
  namespace: home-automation
subsets:
  - addresses:
      - ip: 192.168.50.254
    ports:
      - port: 35055 # Jellyseerr
      - port: 38686 # Lidarr
      - port: 38989 # Sonarr
      - port: 37878 # Radarr
      - port: 39696 # Prowlarr
