---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - ./openvpn-secrets.sops.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./serviceaccount.yaml
  - ./ingress.yaml
