apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - name: webui
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - port: 80
      targetPort: 7878

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - port: 80
      targetPort: 8989

---
apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - name: http-proxy
      protocol: TCP
      port: 8888
      targetPort: 8888
    - name: ss-tcp
      protocol: TCP
      port: 8388
      targetPort: 8388
    - name: ss-udp
      protocol: UDP
      port: 8388
      targetPort: 8388
