apiVersion: v1
kind: Service
metadata:
  name: ugreen-nas-arr-stack
  namespace: home-automation
spec:
  type: ClusterIP
  ports:
    - port: 35055 # Jellyseerr
      targetPort: 35055
      protocol: TCP
      name: http
    - port: 38686 # Lidarr
      targetPort: 38686
      protocol: TCP
      name: http
    - port: 38989 # Sonarr
      targetPort: 38989
      protocol: TCP
      name: http
    - port: 37878 # Radarr
      targetPort: 37878
      protocol: TCP
      name: http
    - port: 39696 # Prowlarr
      targetPort: 39696
      protocol: TCP
      name: http
