# apiVersion: v1
# kind: Service
# metadata:
#   name: qbittorrent

# spec:
#   selector:
#     app: qbittorrent
#     part-of: qbittorrent
#   type: LoadBalancer

#   ports:
#     - name: webui
#       port: 8080
#       targetPort: webui
#     - name: bittorrent
#       port: 6881
#       targetPort: bittorrent
#       protocol: TCP
#     - name: bittorrent-udp
#       port: 6881
#       targetPort: bittorrent-udp
#       protocol: UDP

apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - name: webui
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - port: 80
      targetPort: 7878

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: home-automation
spec:
  selector:
    app: arr-stack
  ports:
    - port: 80
      targetPort: 8989
