# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FjkAjvOwesMs9i6NCA40h+qS6qe3QlgkeLXeXmjox7WM1vCC7OBk2Q==,iv:JS1JRFX6QdGaw4clfy65t0iVh2JFJE6GWu/CYa+wV3w=,tag:AbfOvwGbDfUuhva/GC5LkA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWkFUV2tDMUI1d2ZFV0g2
        U2pCdUU2YkhvZFpDRFNVS0RYblhQTFBlVUJzCklFRjRDcDBtS2VGdSs5RGpCRUpS
        UHdTMkVGZ3BqU1B0S0FrRDhTTWw1Zm8KLS0tIFBLYXlNaVBsK0JSZC9RK2tBTEhF
        eCtCZDZrM1pWM29oblFJbjYxTEFuM0UKYTWvCJ/nEQUOezhZFzcNLhmhJy8ov+W+
        /dbJ0O0BIT+0bR5oS/SyszVdFxNS2Sl+TeLCLr8cV3F6/tNlfnGxCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T17:20:39Z"
  mac: ENC[AES256_GCM,data:LEysb2SFyIDY0CXKXyUDdEeAcNKBgfgMz5YVS3IW3XWgnBB1fynWrCs/Bh2kos8Nw5+o5LilhB1kmNpdMKsQzzNolaSRSHRH21rskvXfW58JFK4P7KQTFeJnk7rIIIFLBYWd7WH5liYgb3pfBwfbzoZLh1rowEwKS082VJxfVPM=,iv:lIsFloQdJYQf+ItUhkbd2UzN7zxMAdgawPfjjaDwLlY=,tag:4oVHDJBHsSmFA90ILYfALw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
