apiVersion: apps/v1
kind: Deployment
metadata:
  name: delugevpn
  labels:
    app: delugevpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delugevpn
  template:
    metadata:
      labels:
        app: delugevpn
    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: delugevpn
          image: binhex/arch-delugevpn:latest
          # command:
          #   - /bin/bash
          #   - -c
          #   - while true; do sleep 3600; done
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
            runAsGroup: 1000
            runAsUser: 1000

          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 200m

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            # - name: UMASK
            #   value: "002"
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "protonvpn"
            - name: VPN_CLIENT
              value: "openvpn"
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: openvpn-secrets
                  key: OPENVPN_USERNAME
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: openvpn-secrets
                  key: OPENVPN_PASSWORD
            - name: DELUGE_ENABLE_WEBUI_PASSWORD
              value: "yes"

          ports:
            - containerPort: 8112
              protocol: TCP

          volumeMounts:
            - name: homelab-storage
              mountPath: /config
              subPath: deluge/config
            - name: homelab-storage
              mountPath: /data
              subPath: deluge/data

      volumes:
        - name: homelab-storage
          persistentVolumeClaim:
            claimName: homelab-nfs-pvc
