apiVersion: apps/v1
kind: Deployment
metadata:
  name: delugevpn
  labels:
    app: delugevpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delugevpn
  template:
    metadata:
      labels:
        app: delugevpn
    spec:
      securityContext:
        fsGroup: 1000

      containers:
        - name: delugevpn
          image: binhex/arch-delugevpn:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_ADMIN
            privileged: true
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
              ephemeral-storage: 1Gi
            requests:
              memory: 512Mi
              cpu: 200m
              ephemeral-storage: 512Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "protonvpn"
            - name: VPN_CLIENT
              value: "openvpn"
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: openvpn-secrets
                  key: OPENVPN_USERNAME
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: openvpn-secrets
                  key: OPENVPN_PASSWORD
          ports:
            - containerPort: 8112
              protocol: TCP
          volumeMounts:
            - name: homelab-storage
              mountPath: /config
              subPath: deluge/config
            - name: dev-net-tun
              mountPath: /dev/net/tun

      volumes:
        - name: homelab-storage
          persistentVolumeClaim:
            claimName: homelab-nfs-pvc
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
