apiVersion: v1
kind: Service
metadata:
  name: delugevpn
  namespace: home-automation
  labels:
    app: delugevpn
spec:
  type: ClusterIP
  selector:
    app: delugevpn
  ports:
    - name: web-ui
      protocol: TCP
      port: 8112
      targetPort: 8112
