apiVersion: v1
kind: Service
metadata:
  name: delugevpn

spec:
  selector:
    app: delugevpn

  ports:
    - name: webui
      port: 8112
      targetPort: 8112
    - name: privoxy
      port: 8118
      targetPort: 8118
    - name: daemon
      port: 58846
      targetPort: 58846
    - name: incoming
      port: 58946
      targetPort: 58946
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr

spec:
  selector:
    app: prowlarr

  ports:
    - port: 9696
      targetPort: 9696
      protocol: TCP
      name: http
