apiVersion: v1
kind: Service
metadata:
  name: qbittorrentvpn

spec:
  type: ClusterIP
  ports:
    - name: web
      port: 38080
      targetPort: 38080
      protocol: TCP
    - name: privoxy
      port: 38118
      targetPort: 38118
      protocol: TCP
