apiVersion: v1
kind: Service
metadata:
  name: qbittorrentvpn

spec:
  selector:
    app: qbittorrentvpn

  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: privoxy
      port: 8118
      targetPort: 8118
      protocol: TCP
    - name: jackett
      port: 9118
      targetPort: 9118
      protocol: TCP
    - name: torrent
      port: 58946
      targetPort: 58946
      protocol: TCP
