apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard

spec:
  selector:
    matchLabels:
      app: wireguard

  template:
    metadata:
      labels:
        app: wireguard

    spec:
      containers:
        - name: wireguard
          image: lscr.io/linuxserver/wireguard:latest

          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Stockholm"

          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 256Mi
              cpu: 500m

          volumeMounts:
            - name: homelab-storage
              mountPath: /config
              subPath: wireguard/config

          ports:
            - containerPort: 51820
              protocol: UDP

      volumes:
        - name: homelab-storage
          persistentVolumeClaim:
            claimName: homelab-nfs-pvc
