# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFV3dpZXQrOFRPd1E2ejZX
        c280RWNGeWhJeVljQVZLUTVBV2lLcXljbldnClB4YXB3K1dIVitwUW1pZXRVeHJk
        L1ZTTDVIclZnaXIydnBhbm9oUkw3SGMKLS0tIGt6NTgvakJoTWE3Mkp5SmlRVUNR
        V2hOMlNkbEk2TEc2Rndvak93VzVocjgKkPZ+huL6e4PatlP8uCnWTkFJPhLh/PQU
        vqIL1t33cKmLYtC2Xi1bsOUEHiHF+rPBNon/c1eJnrxyKyu6WIwoGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T15:02:12Z"
  mac: ENC[AES256_GCM,data:E9JITiOJCSCsDvt/yKWc8ogsJuaJ5Zayzq7aykKT0YBTynJky3sTyZX0MSp4zb5MYmI+IYWjzOo1H2mLOXjCwG8lGOq7gGzsh54ZAtvPHsNtEUZkw0oFMQmfK8SR9sukm3GV4gEfbZACR+qar1xtxFcIIlR7f22TiZwbuEdSDbA=,iv:y/rF0ySiTSSSOcBQN7JRoa/wvfQRB+uQxxtMKlchf48=,tag:LF3q72pY6wu/DCq3m6uRgA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
