# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTnZPdnM0ZnZrckZEM2Vz
        cnNOZkhJZThTRU84czhnQzNTSUl4UG02RjI0ClE0OWRmb2JhYW5hYTdka0xEVXEw
        NnpOVVZ2K3dSM1Y4aFhYam90M2ViaEkKLS0tIHg5dEMyVWtBL1NuWWlFRFRsL21t
        Qy93dTR4VUc3M1B1VExVY0ZSdjF6VzgKdANrDPHR/9bo/nPJTk4fr5JrLCmPQIY7
        GjHblxrYL4m+Q4iCZIt1NGdML4RJblwr+vWDtWbMIZkZ6vnkbi+PAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T14:15:39Z"
  mac: ENC[AES256_GCM,data:zHVHHFxBmXbDWF68Yy8W7kUZYxZvh+KpJ8VSJ9K8uofwYrzu88FxzM6zwchi7jNOFaTs4OZYWqrWPDS2PIJ3/BZdOOwSIGPOpPwXiTRFN1dq6nBrVy/+PhJP2txZAE+mgvU5QZ7/wLWoxob8tx1Ftycp7DQBqn3kr7hmzlrrLB8=,iv:iD9oat1JVrJe+igz12r1xlkYChuYZQYNLZXAt/jbdsE=,tag:NcYHCynTErid7LLUYagE9w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
