# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDZvNFBOTEx6c3JHajFz
        WXZXNVNrQ08vSi81cWsrcFFTcEJDTG4vVmpjClNuT0VoSE1CNjd5UjlLcUpYMUk4
        OTRKdjhDejVSRi9GcDlUZ3VTZVRCUlUKLS0tIEs5M3JxVGVxVGNrY3VpSzZzVDRC
        OTh0eXNkcWNlc01ZNFlpOERRcFpyTjQKWMhGILr9OWk/wFDNLUJaDZPGrBr78acZ
        7ytHDDVFI9jWdqUJSsFx9tuGxU4AuLb+yq8cZM60WtuMep6JM+u1aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T14:57:27Z"
  mac: ENC[AES256_GCM,data:f04FaOUPEfvEAGREJ4Ek8wWgLNGOYEhnzvaOvSHcmP2Q1vol0RGH24E3VrKmLx7TZ8PYJyIEtdvyUsnaiet3lF6FS7eHBiturbFNbMT/SAfvL6lGC/6AmrlJsl1W7SwVUSNQ5lLHhJspJ4JYR1uIYnWc+tc65uqItQx7nC0bUFo=,iv:jlhq5vSwXraGYeV00Y/1ZAvsSQ+EG8t6o5Ki+7A+nVw=,tag:0vM9pQzPaijBSQlcU72vKw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
