# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaXNlVXRQanNQMzNDbmdS
        WnorQzRZdHJNcTJEd1VOMlhiQjRsbUdOVmtJCitpZ1NaSEI0NGNNU3F3T0d2Sis1
        QlJOeVhIVmZVVzM2a25saHBKYWxUVlEKLS0tIHJnNjVycTRqMjRON3ZGdWg4RTZi
        WHlOblZaTlVqWWNrdDJNZ2pTZjdOWGsKGtqUUttUqgVtW3dKZVYE+3oJRt7L1ZIG
        uUsbS3eeCEd+pjrzvkpD5zsftU++MFcRSoQAFEA7G8d1mqlmZn2jnA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-25T21:12:24Z"
  mac: ENC[AES256_GCM,data:OaCnI/9HwmXz4bkcsxK8mpub/HY2e4cDm67r2Foe4MQQxX63n1YxOI0i4NdSLmj/TalZUVJHDUvWIvDKVGOjJmwS16NRSvmNehuAEVOZ4TcGhLo0foHWEf1BJG1xVsvmPJQ416fG2i1MKDP+VZtSMmOWYFyUSf9PPQzLf5Y5AII=,iv:agDnrI6oVQ1MuNVE1bpGXdVx0Pzhd1hlVnxodkCaZKA=,tag:zrVSlMbUNmAWW3Mt/3HA3w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
