# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNRHUrUC8wLzFWWWFZZkJQ
        UXRoamJYbkFnVm41Q0E2VC9ZYXdhSjREMENJCnUrOTl5clI2NURsenBHeTUyMFJQ
        T1RER3h6ckl2QTIrZk5Mc1RUQzBGVjQKLS0tIHY3RGU2NTlPSlFYRjZ5UXhEbWpR
        dzZZcGcrakVKMGxIZlpDNEM4SzRVTFEKtlO+l5C7q7tZSudu2f6PzczEntHFQ1/w
        MpFlo7MDbXC5Ivnnol6YpzlB6Q3y68GLxDKD2NHOzngaLU1J5d5sFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T17:44:16Z"
  mac: ENC[AES256_GCM,data:ojfpTq1TkjXLWZWqPXIi0cgRPM24Y0uQaHPwjfA6JmU2vUXqPsK70oaKJOBWisB7cg5DbDEz0wjEpvp1XZPsXL7+c02jjH4WFMcx2ml4ShTWiLCdi1hi1mv9mpLLfA/EdcA5Hq6uWWZtD/QnX4kYYBZZDFf8jUA++Au+zCvUbvM=,iv:448MbQ+qMbBHT7RsJ5k1dt5oSNNmZIWdh4GS7P95xVE=,tag:z9ZvM6rYd1guTD7/1u3FHA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
