apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
stringData:
  admin-user: ENC[AES256_GCM,data:Azq33Lw=,iv:MfWHztOCi08kvX4nvsCSlKomdxV7V6tEd1aAeEFczH0=,tag:UMQZpHfVqi87upzDGaafPQ==,type:str]
  admin-password: ENC[AES256_GCM,data:uLXfCHU=,iv:0Fro+msORWgV3tYPpltYU/v0IoVb+2XxT9zaSP1yGYg=,tag:YjJ2lPccMlKO2YbVsV56xA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcWdnUnVoY2RxS2dyV3lX
        Ym9wcHJBYW9FREJxWmttamlUdGhMY3UrQkNnCmNFOXpzNEpIOGpiSktxeko3LzdD
        dGczTDlQaWgvZXd1OG5SYU5XY1U3K3MKLS0tIC9XWFNrdkVGZWxiTW1jYlBYVEw5
        Wi8xNVI3ekczN3RZL2JpbDBTK1JjTHcKL6EvpRx/bDOyUHSUcwGOeBLUqOJvrvcp
        BHhHFq5NZ9vIkwnusW0cKvMEFq2qV5KAauFgbMx+957izCX53U9hiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-27T20:45:40Z"
  mac: ENC[AES256_GCM,data:Vw+slWbzNQmeNO6qsF9p5FBWy9ymhK0grKieBCijHmFl3HkGF85EGHwuaATfls/L5gYVhudJhjI9LJW1t8WOwkvV0VKUwRqyqahyr+p5VfVUwyKTewqi0UF1i11+uT9t3liQvh3RfTVYUgA8VomMmvoB/kCFUuy4lA+7+uTnGsI=,iv:JOj3ggPvWsrN9O1vkKvxXCgZ8YEmqQ0Fg18aznGssOM=,tag:jcH7XHVqOSfTthwDJ8tYZA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
