# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: 6.61.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    persistence:
      enabled: true
      storageClassName: default
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    service:
      type: ClusterIP
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - grafana.${SECRET_DOMAIN}
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.${SECRET_DOMAIN}
