export const hubDashboard = {
  url_path: 'wall-hub',
  title: 'Hub',
  icon: 'mdi:view-dashboard',
  config: {
    title: 'Hub',
    views: [{
      title: 'Hub', type: 'panel', path: 'main',
      cards: [{
        type: 'custom:glass-hub',
        weather_entity: 'weather.forecast_home',
        weather_locations: [
          { entity: 'weather.forecast_home', name: 'Nynäshamn' },
          { entity: 'weather.forecast_stockholm', name: 'Stockholm' },
        ],
        person_entity: 'person.philip_rutberg',
        lights_count_entity: 'sensor.lights_on_count',
        vacuum_entity: 'vacuum.roborock_s8',
        vacuum_controls: {
          status_entity: 'sensor.roborock_s8_status',
          battery_entity: 'sensor.roborock_s8_batteri',
          current_room_entity: 'sensor.roborock_s8_nuvarande_rum',
          full_button: 'button.roborock_s8_full_cleaning',
          room_buttons: [
            { entity: 'button.roborock_s8_living_room', name: 'Vardagsrum' },
            { entity: 'button.roborock_s8_kitchen', name: 'Kök' },
            { entity: 'button.roborock_s8_bedroom', name: 'Sovrum' },
            { entity: 'button.roborock_s8_hall', name: 'Hall' },
          ],
          mop_mode_entity: 'select.roborock_s8_mopplage',
          mop_intensity_entity: 'select.roborock_s8_moppintensitet',
          consumables: [
            { entity: 'sensor.roborock_s8_huvudborste_tid_kvar', name: 'Huvudborste' },
            { entity: 'sensor.roborock_s8_sidoborste_tid_kvar', name: 'Sidoborste' },
            { entity: 'sensor.roborock_s8_filtertid_kvar', name: 'Filter' },
            { entity: 'sensor.roborock_s8_sensortid_kvar', name: 'Sensorer' },
          ],
        },
        price_entity: 'sensor.bryggan_elpris',
        price_series_entity: 'sensor.elpris_timserie',
        co2_entity: 'sensor.electricity_maps_co2_intensitet',
        fossil_entity: 'sensor.electricity_maps_procent_fossila_branslen_i_elnatet',
        // Verified 2026-07-20: Tibber total = (energy+påslag)×moms, no energiskatt → add both fees
        // (diff 33.96 öre vs moms-only 22.37 öre @ 00:00; consistent ~10-13 öre påslag gap across
        // hours, not the ~45 öre energiskatt would add).
        grid: { overforing_ore: 26, energiskatt_ore: 45 },
        disturbances_entity: 'sensor.sl_storningar',
        departures: { next_entity: 'sensor.avgangar_next_departure', list_entity: 'sensor.avgangar_departures' },
        transit: {
          pendeltag: { next_entity: 'sensor.avgangar_next_departure', count_entity: 'sensor.avgangar_departures' },
          bus: { entity: 'sensor.sl_kullstaplan', line: '861', exclude_destination: 'nynäs', label: 'Buss 861 → Slakthuset' },
        },
        // Kök + Sovrum are bonded to the Arc as surround speakers, so they never
        // appear as independent players in HA. If they're ever unbonded, add them
        // back here — the Media page's tabs/grouping UI reactivates automatically:
        //   { entity: 'media_player.kitchen', name: 'Kök' },
        //   { entity: 'media_player.bedroom', name: 'Sovrum' },
        media_players: [
          { entity: 'media_player.arc_sub', name: 'Vardagsrum (Arc)' },
        ],
        kcal: { today_entity: 'sensor.kcal_idag', forecast_entity: 'sensor.kcal_viktprognos', planner_entity: 'sensor.kcal_veckoplan' },
        // Hälsa page. Oura owns recovery + activity, Withings owns the body —
        // a split by capability, since Oura measures no weight. history_entity
        // is the 14-day series a Lovelace card cannot fetch for itself; every
        // other entity is read live so the panel is never a poll behind.
        health: {
          history_entity: 'sensor.kcal_halsa',
          oura: {
            sleep_score_entity: 'sensor.oura_ring_sleep_score',
            sleep_duration_entity: 'sensor.oura_ring_total_sleep_duration', // hours
            time_in_bed_entity: 'sensor.oura_ring_time_in_bed',
            deep_entity: 'sensor.oura_ring_deep_sleep_duration',
            rem_entity: 'sensor.oura_ring_rem_sleep_duration',
            light_entity: 'sensor.oura_ring_light_sleep_duration',
            awake_entity: 'sensor.oura_ring_awake_time',
            efficiency_entity: 'sensor.oura_ring_sleep_efficiency',
            latency_entity: 'sensor.oura_ring_sleep_latency',
            bedtime_start_entity: 'sensor.oura_ring_bedtime_start',
            bedtime_end_entity: 'sensor.oura_ring_bedtime_end',
            readiness_score_entity: 'sensor.oura_ring_readiness_score',
            hrv_entity: 'sensor.oura_ring_average_sleep_hrv',
            resting_hr_entity: 'sensor.oura_ring_lowest_sleep_heart_rate',
            temp_deviation_entity: 'sensor.oura_ring_temperature_deviation',
            hrv_balance_entity: 'sensor.oura_ring_hrv_balance_score',
            sleep_regularity_entity: 'sensor.oura_ring_sleep_regularity_score',
            resting_hr_score_entity: 'sensor.oura_ring_resting_heart_rate_score',
            activity_score_entity: 'sensor.oura_ring_activity_score',
            steps_entity: 'sensor.oura_ring_steps',
            active_kcal_entity: 'sensor.oura_ring_active_calories',
            total_kcal_entity: 'sensor.oura_ring_total_calories',
            target_kcal_entity: 'sensor.oura_ring_target_calories',
            high_met_entity: 'sensor.oura_ring_high_activity_met_minutes',
            medium_met_entity: 'sensor.oura_ring_medium_activity_met_minutes',
            low_met_entity: 'sensor.oura_ring_low_activity_met_minutes',
            battery_entity: 'sensor.oura_ring_ring_battery_level',
            workouts_today_entity: 'sensor.oura_ring_workouts_today',
            workout_type_entity: 'sensor.oura_ring_last_workout_type',
            workout_kcal_entity: 'sensor.oura_ring_last_workout_calories',
            workout_duration_entity: 'sensor.oura_ring_last_workout_duration',
            workout_at_entity: 'sensor.oura_ring_last_heart_rate_reading',
          },
          withings: {
            weight_entity: 'sensor.withings_vikt',
            fat_pct_entity: 'sensor.withings_fettforhallande',
            fat_mass_entity: 'sensor.withings_fettmassa',
            lean_mass_entity: 'sensor.withings_fettfri_massa',
            muscle_entity: 'sensor.withings_muskelmassa',
            bone_entity: 'sensor.withings_benmassa',
            heart_rate_entity: 'sensor.withings_hjartpuls',
            workout_type_entity: 'sensor.withings_typ_pa_senaste_traningspasset',
            workout_kcal_entity: 'sensor.withings_forbranda_kalorier_senaste_traningspasset',
            workout_duration_entity: 'sensor.withings_langd_tid_for_senaste_traningspasset',
          },
        },
        todo_entity: 'todo.att_gora',
        calendar: {
          entities: ['calendar.hem', 'calendar.arbete', 'calendar.philiprutberg00_gmail_com'],
          create_entity: 'calendar.hem',
        },
        volvo: {
          name: 'S60 Polestar',
          battery_entity: 'sensor.volvo_s60_polestar_engineered_batteri',
          range_entity: 'sensor.volvo_s60_polestar_engineered_distance_to_empty_battery',
          lock_entity: 'lock.volvo_s60_polestar_engineered_las',
          charging_entity: 'sensor.volvo_s60_polestar_engineered_charging_status',
          climate_entity: 'button.volvo_s60_polestar_engineered_starta_klimatiseringen',
          climate_stop_entity: 'button.volvo_s60_polestar_engineered_stoppa_klimatiseringen',
          odometer_entity: 'sensor.volvo_s60_polestar_engineered_matarstallning',
          doors: [
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_dorr_vanster_fram', name: 'Förardörr' },
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_dorr_hoger_fram', name: 'Passagerardörr' },
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_dorr_vanster_bak', name: 'Vänster bak' },
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_dorr_hoger_bak', name: 'Höger bak' },
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_baklucka', name: 'Baklucka' },
            { entity: 'binary_sensor.volvo_s60_polestar_engineered_motorhuv', name: 'Motorhuv' },
          ],
        },
        rooms: [
          { id: 'vardagsrum', name: 'Vardagsrum', icon: 'sofa', main_entity: 'light.vardagsrum',
            default_lights: ['light.vardagsrum', 'light.tv'],
            lights: [ { entity: 'light.vardagsrum', name: 'Taklampa' }, { entity: 'light.tv', name: 'TV-lampa' } ] },
          { id: 'kok', name: 'Kök', icon: 'pot', main_entity: 'light.kok',
            default_lights: ['light.kok'],
            lights: [ { entity: 'light.kok', name: 'Taklampa' }, { entity: 'light.tak_1', name: 'Tak 1' },
                      { entity: 'light.tak_2', name: 'Tak 2' }, { entity: 'light.slinga', name: 'Slinga' },
                      { entity: 'light.koksfonstret', name: 'Köksfönstret' } ] },
          { id: 'sovrum', name: 'Sovrum', icon: 'bed', main_entity: 'light.sovrum',
            default_lights: ['light.sovrum'],
            lights: [ { entity: 'light.sovrum', name: 'Taklampa' }, { entity: 'light.lightstrip', name: 'Lightstrip' },
                      { entity: 'light.sovrumsfonstret', name: 'Fönsterlampa' }, { entity: 'light.spot_1', name: 'Spot 1' },
                      { entity: 'light.spot_2', name: 'Spot 2' }, { entity: 'light.spot_3', name: 'Spot 3' } ] },
          { id: 'hall', name: 'Hall', icon: 'door', main_entity: 'light.hall',
            default_lights: ['light.hall'],
            lights: [ { entity: 'light.hall', name: 'Taklampa' }, { entity: 'light.hall_spot_1', name: 'Spot 1' },
                      { entity: 'light.hall_spot_2', name: 'Spot 2' }, { entity: 'light.hall_spot_3', name: 'Spot 3' } ],
            scenes: [ { entity: 'scene.hall_koppla_av', name: 'Koppla av' }, { entity: 'scene.hall_klart_ljus', name: 'Klart ljus' },
                      { entity: 'scene.hall_concentrate', name: 'Fokus' }, { entity: 'scene.hall_las', name: 'Läs' },
                      { entity: 'scene.hall_nattlampa', name: 'Nattlampa' }, { entity: 'scene.hall_fa_ny_energi', name: 'Ny energi' } ] },
          { id: 'office', name: 'Office', icon: 'desk', main_entity: 'light.office',
            default_lights: ['light.office'],
            lights: [ { entity: 'light.office', name: 'Office' } ],
            scenes: [ { entity: 'scene.office_koppla_av', name: 'Koppla av' }, { entity: 'scene.office_concentrate', name: 'Fokus' },
                      { entity: 'scene.office_las', name: 'Läs' }, { entity: 'scene.office_nattlampa', name: 'Nattlampa' },
                      { entity: 'scene.office_fa_ny_energi', name: 'Ny energi' } ] },
          { id: 'badrum', name: 'Badrum', icon: 'shower', main_entity: 'light.badrum',
            default_lights: ['light.badrum'],
            lights: [ { entity: 'light.badrum', name: 'Taklampa' }, { entity: 'light.spotlight_top', name: 'Spotlight' } ],
            scenes: [ { entity: 'scene.badrum_nattljus', name: 'Nattljus' } ] },
        ],
        // No whole-home Hue scenes exist yet for Kvällsläge / Film (see docs/hue-audit.md).
        // Philip needs to create both in the Hue app (so they also sync to HomeKit), then this
        // array should be filled in as:
        //   scenes: [
        //     { entity: 'scene.<confirmed-id>', name: 'Kvällsläge', icon: 'moon' },
        //     { entity: 'scene.<confirmed-id>', name: 'Film', icon: 'play' },
        //   ],
        scenes: [],
      }],
    }],
  },
};
