export const hubDashboard = {
  url_path: 'wall-hub',
  title: 'Hub',
  icon: 'mdi:view-dashboard',
  config: {
    title: 'Hub',
    views: [{
      title: 'Hub', type: 'panel', path: 'main',
      cards: [{
        type: 'custom:glass-hub',
        weather_entity: 'weather.forecast_home',
        person_entity: 'person.philip_rutberg',
        lights_count_entity: 'sensor.lights_on_count',
        vacuum_entity: 'vacuum.roborock_s8',
        price_entity: 'sensor.bryggan_elpris',
        price_series_entity: 'sensor.elpris_timserie',
        co2_entity: 'sensor.electricity_maps_co2_intensitet',
        fossil_entity: 'sensor.electricity_maps_procent_fossila_branslen_i_elnatet',
        departures: { next_entity: 'sensor.avgangar_next_departure', list_entity: 'sensor.avgangar_departures' },
        media_players: [
          { entity: 'media_player.arc_sub', name: 'Vardagsrum (Arc)' },
          { entity: 'media_player.kitchen', name: 'Kök' },
          { entity: 'media_player.bedroom', name: 'Sovrum' },
        ],
        rooms: [
          { id: 'vardagsrum', name: 'Vardagsrum', icon: 'sofa', main_entity: 'light.vardagsrum',
            lights: [ { entity: 'light.vardagsrum', name: 'Taklampa' }, { entity: 'light.tv', name: 'TV-lampa' } ] },
          { id: 'kok', name: 'Kök', icon: 'pot', main_entity: 'light.kok',
            lights: [ { entity: 'light.kok', name: 'Taklampa' }, { entity: 'light.tak_1', name: 'Tak 1' },
                      { entity: 'light.tak_2', name: 'Tak 2' }, { entity: 'light.slinga', name: 'Slinga' },
                      { entity: 'light.koksfonstret', name: 'Köksfönstret' } ] },
          { id: 'sovrum', name: 'Sovrum', icon: 'bed', main_entity: 'light.sovrum',
            lights: [ { entity: 'light.sovrum', name: 'Taklampa' }, { entity: 'light.lightstrip', name: 'Lightstrip' },
                      { entity: 'light.sovrumsfonstret', name: 'Fönsterlampa' }, { entity: 'light.spot_1', name: 'Spot 1' },
                      { entity: 'light.spot_2', name: 'Spot 2' }, { entity: 'light.spot_3', name: 'Spot 3' } ] },
          { id: 'hall', name: 'Hall', icon: 'door', main_entity: 'light.hall',
            lights: [ { entity: 'light.hall', name: 'Taklampa' }, { entity: 'light.hall_spot_1', name: 'Spot 1' },
                      { entity: 'light.hall_spot_2', name: 'Spot 2' }, { entity: 'light.hall_spot_3', name: 'Spot 3' } ],
            scenes: [ { entity: 'scene.hall_koppla_av', name: 'Koppla av' }, { entity: 'scene.hall_klart_ljus', name: 'Klart ljus' },
                      { entity: 'scene.hall_concentrate', name: 'Fokus' }, { entity: 'scene.hall_las', name: 'Läs' },
                      { entity: 'scene.hall_nattlampa', name: 'Nattlampa' }, { entity: 'scene.hall_fa_ny_energi', name: 'Ny energi' } ] },
          { id: 'office', name: 'Office', icon: 'desk', main_entity: 'light.office',
            lights: [ { entity: 'light.office', name: 'Office' } ],
            scenes: [ { entity: 'scene.office_koppla_av', name: 'Koppla av' }, { entity: 'scene.office_concentrate', name: 'Fokus' },
                      { entity: 'scene.office_las', name: 'Läs' }, { entity: 'scene.office_nattlampa', name: 'Nattlampa' },
                      { entity: 'scene.office_fa_ny_energi', name: 'Ny energi' } ] },
          { id: 'badrum', name: 'Badrum', icon: 'shower', main_entity: 'light.badrum',
            lights: [ { entity: 'light.badrum', name: 'Taklampa' }, { entity: 'light.spotlight_top', name: 'Spotlight' } ],
            scenes: [ { entity: 'scene.badrum_nattljus', name: 'Nattljus' } ] },
        ],
        // No whole-home Hue scenes exist yet for Kvällsläge / Film (see docs/hue-audit.md).
        // Philip needs to create both in the Hue app (so they also sync to HomeKit), then this
        // array should be filled in as:
        //   scenes: [
        //     { entity: 'scene.<confirmed-id>', name: 'Kvällsläge', icon: 'moon' },
        //     { entity: 'scene.<confirmed-id>', name: 'Film', icon: 'play' },
        //   ],
        scenes: [],
      }],
    }],
  },
};
