---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: security

resources:
  - postgres.yaml
  - redis.yaml
  - secrets.sops.yaml
  - helmrelease.yaml
  - ingress.yaml
  - oauth2-config.yaml

commonLabels:
  app.kubernetes.io/name: authentik
  app.kubernetes.io/part-of: homelab-security