apiVersion: v1
kind: Secret
metadata:
  name: authentik-secrets
  namespace: security
stringData:
  #ENC[AES256_GCM,data:SD+Phclsdj8jpuW1k6+lBfCX5hWF1P4=,iv:uF47JKg/ah3vz8sw7AsoD9PkdgvDQcE3PG1nBe5mDqE=,tag:7zlg7XQNe6gxv4hEDgJJ4Q==,type:comment]
  postgres-password: ENC[AES256_GCM,data:+jTS+2mu0nLlF9m+mzd1WaYpTtlx5TPx7O3rUWBRgawPvgfr6rhhnZ3USZ0=,iv:dOUgDDJPY7i0je0chEQrGkihxrpc5JxkTdkaVFMl9a8=,tag:xw0OjqQ0Xcoje9chP3ZDNA==,type:str]
  #ENC[AES256_GCM,data:QHQyoRvofVQHMYgTb2TyIKzn,iv:wQAmmUPwRgbKJ+EYBtxdIbXaeHne60pKbO5CiaaEO+w=,tag:Pqp87sm0Xvt6CXcPe1lySg==,type:comment]
  redis-password: ENC[AES256_GCM,data:bjMz5V1StabkXBaZQYw/B7ftbyfx2qGpyID+InYUh8PH/JzP29xZk6lqPPE=,iv:7q80nyTWABi/VqdPTTC3qqvNxgA1BvHX+kiACFSiTE4=,tag:Nmc0CGYRlxIWtyH34ye37g==,type:str]
  #ENC[AES256_GCM,data:nyfzLUM5wi5YdL2VX/p0FljkwiOP13ZVFEU3yrXvsMDrhliFcNzbeV2t6G5x8GOyi8VTz5onUWS/fE4U/ZE=,iv:S0OJbyBM3D511ylTC58qClkdIahPuzlm33+lemEGmXE=,tag:ysd0/pEn7Omi+rcH5/zkDQ==,type:comment]
  secret-key: ENC[AES256_GCM,data:v6SvTi9NEt9xrEq41esoIqli7O8HiQPOeVqNYbwdfmSUqfMATnRInDjlqwTtz51tVu0nmC7/wEcohPvmD6hqTv1c1hc=,iv:y1lJScH5+yFEbOawTmSBH+Dp4j0UL+1Z7aBWsmAMgZY=,tag:IYfp7ErdW8A5fmiMgkauNw==,type:str]
  #ENC[AES256_GCM,data:nE4Qxb2xzMrB+HxHXJk94LDs6Wetr2Fvu2/dP5scv5VQNQKAknCpXIrSKQw=,iv:4V2q+X0FS4f40Sfiej2y0PsGkTSBI3wlVs1CdiDYRiY=,tag:BFqZheVNc7cu4d4xXNcscQ==,type:comment]
  bootstrap-token: ENC[AES256_GCM,data:yipmy/o/nf593pTbx8hdYDr4sTeTLb4JL2047J47dkvpLwjcThcfH7QAeyY=,iv:RVR7LXETLSPltkeeWJ8HZ2nm3IxYEE9JrDvtcindiF0=,tag:/VlrPSH4eUSpz5ZO7HwRxw==,type:str]
  #ENC[AES256_GCM,data:gvcq3ZbQ4GfqR3lHiJ/81H4GCsAyXp8TaFiU4Xf4,iv:3OiaqxyJKPGWTc7UL3fgAY7O4bUPuMUo+QvQJoNHT68=,tag:7Ki+J+PZqveGdgrJpFN+mQ==,type:comment]
  #ENC[AES256_GCM,data:0CjSeLB/LkCAwVRC9Fy/Cdy3qnWinH2nWfdQKw==,iv:0bRyzFmsSRuj4rv6goXxFmaQRqSiI5olqaDXIZJ5uzU=,tag:7unlcOS1wey6pPNn0EuoVQ==,type:comment]
  #ENC[AES256_GCM,data:2xEjb/P6XLvW0mWCOxC+9c8=,iv:v17OCy5C0IX18W53pGL8EIJdR8JxPa7atK9qOM1ALx4=,tag:0Vg7rPEV0qf5hwnSo+Xu9g==,type:comment]
  #ENC[AES256_GCM,data:ZxAeAZqStzOyF0CPl89XChM9qTeq1yzy29qnNwyRF11walG1nrQ4BeU=,iv:gVeR2aRVKSeoVXXLGkFsLjV/CRgZcwrYT5nUha1h3Cw=,tag:oWrKKyfjnY6EdUX8yF+2Vg==,type:comment]
  #ENC[AES256_GCM,data:7qbcC/9DAowgUHwYqLCM352qeKN+Wi5eIZ78KNFpGiKBnERx8jg5Iac=,iv:Vzo/nQpn3H479TWO77V1t84/0IVTPfOEa9Js54AIsaw=,tag:qLqcAeUji8lCi7EBJUAFuQ==,type:comment]
  #ENC[AES256_GCM,data:8CHFcwoIxemuq0L4NR2kOghu5E3DeQj5AFTdQ+mh6kr2IMc=,iv:iBxcYlNf8GLIjWH+ei03P9AKQsHGJxh/FPKuohKWc1I=,tag:MxMa+qXDK2yIyVfB9C5EAA==,type:comment]
  #ENC[AES256_GCM,data:Ua3Tanq7A4CYuHKeC1FeV0Lxu+Pf,iv:WGvpib0wD70PpjeenbQGmSaYp4HyVrkkIrP0zhGCqF0=,tag:OcJGvlcV2DGRUGU5jgvnnQ==,type:comment]
  #ENC[AES256_GCM,data:STZrQayqf+8DS2K1/x28/RxCZZpReg==,iv:uH4IVmv6IUuBmxVhUTv+4bWcWIA4oXzr3iRteH1QVoM=,tag:hIjkRze22I4o9062INTiQw==,type:comment]
  #ENC[AES256_GCM,data:fIIg3MT6H/A0WTjdKy+qhewCE32OajrMzcZjBa7nmX0shL/4dKYEWp3WUA==,iv:G40JcaXmJoZ7Gg/VJyfNsSa/GuiG7xMCTERFB/lqwQM=,tag:Q4DMZWjY95HFRVrvCcNrWw==,type:comment]
  oauth2-client-secret: ENC[AES256_GCM,data:JpJ49vFyAuC6yzhrtH4jTf1B58GaloX1ZydAtyM+XvbINcxEVhGkND8eF+0=,iv:gDqBX9SI8f/hg1W+sJYzcPrroPolxYzD4CsHCMOUV50=,tag:8h/bMWMyKAL9ksrqbns/cA==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvR1VOS1hXWmRheEs2YXds
        M2g3aWwyNHlRQjk1dklvNEY5aWVGUEJiaG5jCjJMZkc2RzVzWkszY1Q5eG84NjdT
        d21SQWphRGxKcStKTWF6WjBpTVo1c2sKLS0tIGRVSG53K2pHa3JJRzdJelN1Qm8r
        N1VkeGdEYzM1UUdOTlZCYWNGVjZqSkEKaSA87E83xAhBhUEEnlSlBkSUAhx7OPik
        yF7HBCITfndNKcWTsWzgRsqSG5t8BccFm3uXrtcSGQeovEBn4kMI+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-08-29T18:22:15Z"
  mac: ENC[AES256_GCM,data:0EIpt6ok2lD5lq3YRhWQ56T6wNEmhyLVHbIGf1UkD3oHbSDEbadFz3SZpdbCw32IYQUTA6lnKfO0+e8HYgQzCwjQ5OnpBZZ6Ok2QJtn9TAySSx+cVV8dgfc7wSb4BbS/jeYzaD7cTJu+ZNhQajZOpBNZ8Oax9vI8f/BVmF6XHeQ=,iv:ecPuusXuKwtwg4Wxb0wCTqFMSexwDWWqFCMH99iZUfQ=,tag:MLI35Ml2QHAOeL0ut+EFqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
