---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-mailserver-tls
  namespace: home-automation
spec:
  secretName: docker-mailserver-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - mail.rutberg.dev
