apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver-environment
  namespace: home-automation
immutable: false
data:
  TZ: "Europe/Stockholm"
  OVERRIDE_HOSTNAME: "mail.rutberg.dev"
  POSTMASTER_ADDRESS: "postmaster@rutberg.dev"
  TLS_LEVEL: "modern"
  POSTSCREEN_ACTION: "drop"
  UPDATE_CHECK_INTERVAL: "10d"
  POSTFIX_INET_PROTOCOLS: "ipv4"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "1"
  ENABLE_SPAMASSASSIN: "1"
  ENABLE_RSPAMD: "1"
  MOVE_SPAM_TO_JUNK: "1"
  ENABLE_UPDATE_CHECK: "1"
  SSL_TYPE: "manual"
  SSL_CERT_PATH: "/secrets/ssl/tls.crt"
  SSL_KEY_PATH: "/secrets/ssl/tls.key"
  SUPERVISOR_LOGLEVEL: "warn"
  ONE_DIR: "1"
  FAIL2BAN_BLOCKTYPE: "drop"
  SPAMASSASSIN_SPAM_TO_INBOX: "0"
