apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: home-automation
  labels:
    app: mailserver

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver

    spec:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: "OnRootMismatch"
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mailserver
          image: ghcr.io/docker-mailserver/docker-mailserver:latest
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                - NET_ADMIN
                - NET_RAW
                - NET_BIND_SERVICE
                - SYS_CHROOT
                - KILL
              drop:
                - ALL

          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 200m

          envFrom:
            - configMapRef:
                name: mailserver-environment

          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: submissions
              containerPort: 465
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
            - name: imaps
              containerPort: 993
              protocol: TCP

          readinessProbe:
            tcpSocket:
              port: 25
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 5

          volumeMounts:
            - name: mail-files
              mountPath: /tmp/docker-mailserver
            - name: homelab-storage
              mountPath: /var/mail
              subPath: docker-mailserver/mail
              readOnly: false
            - name: homelab-storage
              mountPath: /var/mail-state
              subPath: docker-mailserver/mail-state
              readOnly: false
            - name: homelab-storage
              mountPath: /var/log/mail
              subPath: docker-mailserver/log
              readOnly: false
            # - name: homelab-storage
            #   mountPath: /var/lib/amavis
            #   subPath: docker-mailserver/amavis
            #   readOnly: false
            - name: tls
              mountPath: /secrets/ssl
              readOnly: true

      volumes:
        - name: mail-files
          secret:
            secretName: mailserver-files
        - name: homelab-storage
          persistentVolumeClaim:
            claimName: homelab-nfs-pvc
        - name: tls
          secret:
            secretName: mailserver-tls
