apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - roundcube-deployment.yaml
  - roundcube-service.yaml
  - roundcube-configmap.yaml
  - ingress.yaml
