apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - ./secret.sops.yaml
  - ./postfix-accounts.secret.sops.yaml
  - ./mailserver-local-pvc.yaml
  - ./service.yaml
  - ./deployment.yaml
  - ./config.yaml
