# mailserver-local-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mailserver-local-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-provisioner
