apiVersion: apps/v1
kind: Deployment
metadata:
  name: roundcube
  namespace: home-automation
  labels:
    app: roundcube

spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundcube
  template:
    metadata:
      labels:
        app: roundcube

    spec:
      containers:
        - name: roundcube
          image: roundcube/roundcubemail:latest
          imagePullPolicy: IfNotPresent

          env:
            - name: ROUNDCUBEMAIL_DEFAULT_HOST
              value: "ssl://mail.rutberg.dev"
            - name: ROUNDCUBEMAIL_DEFAULT_PORT
              value: "993"
            - name: ROUNDCUBEMAIL_SMTP_SERVER
              value: "tls://mail.rutberg.dev"
            - name: ROUNDCUBEMAIL_SMTP_PORT
              value: "587"
            - name: ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE
              value: "25M"
            - name: ROUNDCUBEMAIL_DB_TYPE
              value: "sqlite"
            - name: ROUNDCUBEMAIL_SKIN
              value: "elastic"
            - name: ROUNDCUBEMAIL_PLUGINS
              value: "archive,zipdownload,managesieve"

          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 100m

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30

      volumes: []
