apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: home-automation
  labels:
    app: mailserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: mailserver
  ports:
    - name: smtp
      port: 25
      targetPort: smtp
      protocol: TCP
    - name: submissions
      port: 465
      targetPort: submissions
      protocol: TCP
    - name: submission
      port: 587
      targetPort: submission
      protocol: TCP
    - name: imaps
      port: 993
      targetPort: imaps
      protocol: TCP
