apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-ugreen
