apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-movies
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-series
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path-provisioner
