apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-automation
  namespace: flux-system
spec:
  targetNamespace: home-automation
  interval: 30m
  path: ./kubernetes/apps/home-automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
