apiVersion: v1
kind: PersistentVolume
metadata:
  name: homelab-nfs-pv-home-automation
  namespace: home-automation
spec:
  capacity:
    storage: 7.2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "192.168.50.254"
    path: /volume1/homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelab-nfs-pvc
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7.2Ti
  volumeName: homelab-nfs-pv-home-automation
