apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homelab-nfs-pvc
  namespace: security
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7.2Ti
  volumeName: homelab-nfs-pv
