apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
stringData:
    FTLCONF_webserver_api_password: ENC[AES256_GCM,data:xOmGckvXZYP9gavD,iv:ULMeUkYu93HkZ0RUxDpmbmsd4UY+MttM7w4qTZ7Wiy8=,tag:uwDTF+4csMxiaHcjljK3PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTURwa3lUTVd0N0h3UnNW
            TmRueC81TDBWVmVxVGtVMUd6WkZLSUxvSXhJClJUYWVXaXdMQjlyeG1aajNMUlRh
            dUJJNWJuTjFqSGZRbmFTVTJsQnp4NDQKLS0tIHcrRU1KdlhDb3J6Z2FqdkdQS1ZC
            NWJ0RTIyVlBFSnBMSjJPbXZVTEdlWFEKCRK1300lSUHYH7QnWcWf/IxTPPLKN0mX
            lXH1rGAz4Lcg5y32+s79LkruPxyaY35zTgLJubI+KvCSWXjVaxh6NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-22T19:41:02Z"
    mac: ENC[AES256_GCM,data:Fn98AfVdj/8BTw09R+1Eo/pu56hYU4zH40m+cDlb/1tLP8VsnHd6dqBgsuHxbGqBEU2eTqgV+W47fcSn6XQVj7BxF4KOVNVZaVpWQofDuti1if6NK5CUJqUKVbymldUEhuDeSdTkFaPQ7dZyhpKoFz9VgO87StN7EKOvnPN6QIM=,iv:+rDRzJF4v+tz4qYUf3xIbOHLEwTbgjZ0zhn4czlQJhg=,tag:VafBGhvnoaW9jr2p4tMF0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
