apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:6uL0aBU778jtxdI=,iv:u8D5GzS4Oh035ZX9XzR/ydLuW12+56NNlcJjdKGXWsM=,tag:xodsAP/5c+dE4fCzCr9ooA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eDlYMXZFZ3V2cExZL1dT
        VmtlYlpqNkJhc1AvYnVFYU9MaS9XWFNWM1c4ClllS0IxcTNhdGNsby9DRVhVenFO
        Mkxqb1V2WXBsRlFFQmNTQ2NCWmM1WlkKLS0tIDd3MXlsdVF0QU52MlFSWHpzWE13
        U0paalkvUy8rclJqeTJENXFZeFIzVW8KYmaJpvH6/pzyYiIGEteBAwI+oB8muwsE
        GBwbU50Z+F3vfE5fXlKLugaHYtv4pcSKC656linfQOoZx/g6kllfHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-17T14:15:39Z"
  mac: ENC[AES256_GCM,data:0k35WfAmwMcH1vWNkqiWrQlZMd+pEmE9QiXhKti+izot5aoJcZM2S4PeRczVAGtIB0qWyEDXivT227DU/4urcICxmKQRuNWTcBAWSHmpah0Qc6piHEWy0tdQOhg21/MglrfeepcVsFTInCyT80f6F5OTlSaXaKmhM55ZTbhLWQo=,iv:M871135Q8U+70K3ffEteHmGUuIyPPiblmnpL1mTvqgw=,tag:HGxBt7A6Pxv0JJ03Uo9tVA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
