apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:SokzyLOqtd8jeqE=,iv:VR7ZCrVrfWNDFW3G/WpV4R37pPMdQ6ubl1H5n7YuhJs=,tag:PBC/9+nXJ/uRypy0Km90Iw==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:+aiWow0C/bwGt3oeCvc=,iv:XupVL/4H9Yr8KvCQSvJDJp7Cj6vWiOQ1OjjMdFqnMb8=,tag:8nnC8sZSjhDS7IoMFub2ig==,type:str]
    NFS_PATH: ENC[AES256_GCM,data:rYSMrKryilZZKHXKqX82Yg==,iv:UOXdxF/OiI2s+Bhn/Lr44NoKJvoDVFhCiNIRKptJ1cM=,tag:1tndwKreQuHyh4IZZTL5dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dksrenhzRmZpejZ4N2Zi
            dlo4QmNwM3QrVElZMGFrN0RGTkdNS0lCWldRCmtFdG05bS9vdmlWWUJ6aGt3SjNP
            Z3A0bVFBMm1vWHZaWE5qUXczSVNETGcKLS0tIHFUMUNWQnIxMkg4OUYxL2RVSGg2
            SVVzQy94U2VEWU5ZOVJiUDlGOTlJM3cKAhCrfcolWAnMzlqwk7ixHKWlUGjS4Rwy
            gD1RzKb0sTsgJTIXqfimi+8w9Na2u+mFmcwMdwNJmL5cAMH83S7O3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T16:05:40Z"
    mac: ENC[AES256_GCM,data:qTiEJxbTmJRhKr7eb7/Pnn39eNy4ZLIk5KqeLArRg/Mt/SQgHda2UFqTL2GzxwKIenzK2mOzg9p/t6L6vgSkJPBuHZli3X/9cDMDkGhqeHy5NkOcQ9nrvWjLQdsWo5nK6TM7pG3iqLB0z7F53BuzgR1B912J3DMHtOWPbzsO0tY=,iv:Uf+Apx8Pvh9MkPUt4de7qF3ep86IHj+aNjA8/oI/RRc=,tag:bvblOG4cYy1IvTmIKDbKjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
