apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:feQTPK/BDCduCQijXGYRqxmfFjJfRoa9KPVOGdRwp3glpwd6Kheo/73wBid7TmdXMKTsNd7lsVpo9fcPvYy3YwJtHPEoOl23eD4=,iv:zf0IIVoMZ9qAqXjDE3uabamr5BrnlO0J3biNU9kKflg=,tag:pB+k6A+XR+MFGe/xeYrXVA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc0JHZTlxL2hVY2ZuSjND
        c2ZlYWtVT2Z2blIwbk5FNmkzUzYyNVNMYm5ZCmlGQmJ5Y0JPZ2I3QlY5cFFwY1Bu
        dFBzOXRSYVBTS0VBeVhoMXhwd0tTUm8KLS0tIFEreWJpK0FjMjRTMUUrU2o5SG1S
        dm4vTWdSQi9OQnRvbW1XbndDN1RVN2MKwtoVdpBMFLtY0VQccTDZdMGn/7B27tna
        vDuFBnKHn1A/0iYLLCnluXIplpkjjx5CGdPE85YmDdk8xbXYri7tYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-24T17:20:38Z"
  mac: ENC[AES256_GCM,data:BDLVmW0twxxgO/0TVb1reXo8BiWx1sQJ3DZ7xymqIx1OZ6IxoiZauj0ZxfLfXrKb4DGrg5YaW/x5mDVk6Q2j7hr6LvbiTDe9uSev9qEZCEnvSEQkWHvuExiMJ0r0VFskKVhfvyiPn41ET62Okv0/YJGh1mMmiwrCzqN2QATS3Og=,iv:2qnL4IE6hE/mM33aoPAmMsk0pTWAZmZQHn/rB+2b+DE=,tag:edvFZKG7odCdJQ5YljAQpA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
