apiVersion: v1
kind: Service
metadata:
  name: pihole

spec:
  selector:
    app: pihole

  ports:
    - name: dns
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: web
      port: 80
