---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extracted-movies
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-path-provisioner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extracted-series
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: local-path-provisioner
