apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-ugreen
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.11.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      runOnControlPlane: true

    node:
      enabled: true

    linux:
      enabled: true

    feature:
      enableFSGroupPolicy: true

    storageClass:
      create: true
      name: nfs-ugreen
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      mountOptions:
        - vers=3
        - nolock
      parameters:
        server: "192.168.50.254"
        share: /volume1/homelab
