apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-ugreen
  nfs:
    server: 192.168.50.254
    path: /volume1/homelab/movies
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-ugreen
  volumeName: movies-pv
