apiVersion: v1
kind: Secret
metadata:
  name: claude-db-secrets
  namespace: default
type: Opaque
stringData:
  MCP_TOKEN: ENC[AES256_GCM,data:coomYc66U8lNHx4i2qX9MQ3KTyleCdh6ahWoJ8/Jz1JYtgWNuGSRL6GRR+uAKmhp+dEcY3DoDAUfNv8jG7zOxg==,iv:ge7KcOCKGnKKCdl+YR84wOf8GlivkTb9ijpu8ni77Ac=,tag:UG6GrnUAjN18zzjdYsW5bQ==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZUFmczBCV1JlRkhZaFBX
        bmJVMXFRODNZTGMyTHpINVBHN2dydStoQ3pNCjZ4Mm9vS1dDbWl3dTJVbjZkWVZF
        NnVRQTRiOFhGRit2QzEweGJWekJtY2cKLS0tIEVhNUt5YTJIU0VXa0xiQTEvNGR4
        ZG9nN1F4aytVQmJteFZsekwrbTVLWVUKqf3Cc5z8r3FYR9V7Z5jFCio27BENhwBz
        cUUghLvQxkObVuGpAAL1gqgyBkYBGObXVwz1Tf43tqrkaBnclN+yQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-02T20:44:15Z"
  mac: ENC[AES256_GCM,data:do+yCA03EvUOL05UbLDbKa/SK8xIkf0ca+Lpn1GrKJRnm1Z7VtRYVmLI8AR9/6bQekKwklyBC9jGusukF+ALXJyl+J3tXQcwdoNF+ry05lNWCdcdhjHTWpkb5NWG4lOWpqN1yHgDmvFwfUFdvRwtVmHU+ZkqYbd3w0dY0iPTaRw=,iv:/THmvbEEEa5JWIUv1XiueW5algx7ej6M8hUs1bXQqLk=,tag:HBa6mANtZ1caa38y5OlZUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
