apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun

spec:
  selector:
    matchLabels:
      app: gluetun

  template:
    metadata:
      labels:
        app: gluetun

    spec:
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun:latest

          resources:
            limits:
              memory: 128Mi
              cpu: 500m

          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8388
              protocol: TCP
            - containerPort: 8388
              protocol: UDP
