# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:aIAqzkDCkzdYLjflscd3YmTEfDUdprxL3SLRh9xD1mqxI/7M1YyxpdgdUl9qwliPwsO+AdCIdCM0TuqohSuVasrlkPBKQs8bA8OpswHhiq8=,iv:raTwxL1mWex9q3yzEH2TEpfeMQkh//6MnsFb+dIiMy4=,tag:+K+apad5OOAvrp4BzvOadA==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSEptUUdkK0trOS9iU2pU
        UnRWRWQycTNMeHprd2hhUmJHV3lueG04NkVvCm1GYVkzK1pBaHdFT2N6UXlkeTlW
        V0dXSStXSFZzMW1HSk5tRUdGbzl0T1UKLS0tIEVKUGFQWDk5dFdZd2tudHV4ZFVy
        VDVCWFJEOEhhYmM5ZFhLNEhFS0hIQkkKMu5M+cGzGUBU8KQWoaQxCIIjX5KXCG5L
        NqYHbyYdD6kArtSz3cSBxwKrMZBvXktwQCPm9GG5zaYlPtuZztWGxg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-18T16:26:04Z"
  mac: ENC[AES256_GCM,data:tWbj4KehQjNSpcMuO1OEUx5gfCJuZeBZ579jK5V1g9VuCfuHJcUe7HIcA8uO3skLizbyAPpvDPuPV6Gds+mJmP6+WH/QmQuoyQEQm19juxBMn/02wDGRIRy1wdaueC2VwjzanNWsu3M3risfFAeueIZvoWsEtOKKn/cXdDjyuYQ=,iv:ZqrdS+bvWwRenlwxiORkjEo78JJpcNEZfUw0xG+gC0A=,tag:umf8/2fW71AJI7LIWQIdqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
