# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
stringData:
  TS_AUTHKEY: ENC[AES256_GCM,data:fyipij4c1/sXAVryBmtp5B74oJUSSSo+UlymINIQ/ETKKxQdRfVjiak4z/n9k7zFsj4ebCsZODND/RAxtAE=,iv:5FYEkn827bgOdlMCbBd3Ix+i70ksEo4nq7BsGNwAS78=,tag:e6r3XGmNkFpdlKYMUTdUFw==,type:str]
sops:
  age:
    - recipient: age10ppc643t645d2ph0czpz64zq9ezj0j9xu0c0mjytm6a34fzulqhqa8pp2k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M2ZTVTF5TFJ4U3Q2MkpX
        czMxcjVUQjVCZHlBSkFkSnJxS3FiYkVoU1RBCm0rbnA3ZFRsc2pBRTE4OEtVaHRE
        V2tTankxLzRieUdmNGlSM0FYTWxWeHcKLS0tIGVVc0llZGhKSWZCSEk5WlNYRXpj
        MjVNK3JDSVRMcFJYaG9scTgrQm05MzQKUvo+Y/GAgN0Luz55ekae2zddG7KvXs2i
        rUUTjzZWCeefzfcPDhu0MzfkCbhphauOAWgvk9N97EzrtsTIXESIaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-18T11:42:49Z"
  mac: ENC[AES256_GCM,data:9R21xSnzY841bkGUQBDT8wAc940grPIPyLm1xie5qSF58Ffnw/9xbOnqhTXHSotrVN9/RMQOOF295/xjYiza6iBdABssXIsWS2Gg3cgBBzvWyHHD/Q2D9c6CdTs/3KvbFvhQZXewp6V2QV6eiEaDFF0j0quu/uUov/VJV/X2lsk=,iv:HbxKD7MMUySnkrT8YhLxNMVjYhQpz+EiL6ICCMKQaLE=,tag:PXXmoGnZPAYCcM5v0c+8Cw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
