apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: observability
  path: ./kubernetes/apps/observability/prometheus
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  interval: 30m
